#include <stdio.h>
#include <math.h>

#include "../include/common.h"
#include "../include/resets.h"
#include "../include/xosc.h"
#include "../include/pll.h"
#include "../include/clocks.h"
#include "../include/io_bank0.h"
#include "../include/pads_bank0.h"
#include "../include/uart.h"

#define XOSC_FREQ 12000000
#define POSTDIV1 6
#define POSTDIV2 2
#define CPUFREQ 133000000 //in this setup should be between 63 and 133 MHz
#define FBDIV (CPUFREQ*POSTDIV1*POSTDIV2/XOSC_FREQ)

#define BAUDRATE 921600
#define IBRD ((8*CPUFREQ + BAUDRATE)/(2*BAUDRATE))/64
#define FBRD ((8*CPUFREQ + BAUDRATE)/(2*BAUDRATE))%64

int uart_putc(char c, FILE *file){

    REG(UART0_BASE + UART_UARTDR_OFFSET) = c;
    while(!(REG(UART0_BASE + UART_UARTFR_OFFSET) & UART_UARTFR_TXFE_BITS));
    return c;
}

int uart_getc(FILE *file){

    unsigned char c;

    while(!(REG(UART0_BASE + UART_UARTFR_OFFSET) & UART_UARTFR_RXFF_BITS));
    c = REG(UART0_BASE + UART_UARTDR_OFFSET);
    return c;
}

FILE __stdio = FDEV_SETUP_STREAM(uart_putc, uart_getc, NULL, _FDEV_SETUP_RW);

FILE *const stdin = &__stdio;
__strong_reference(stdin, stdout);
__strong_reference(stdin, stderr);

void uart_init(){

    REG(RESETS_BASE + RESETS_RESET_OFFSET + REG_ALIAS_CLR_BITS) = RESETS_RESET_IO_BANK0_BITS | RESETS_RESET_PLL_SYS_BITS;
    while(~(REG(RESETS_BASE + RESETS_RESET_DONE_OFFSET)) & (RESETS_RESET_DONE_IO_BANK0_BITS | RESETS_RESET_DONE_PLL_SYS_BITS));

    REG(XOSC_BASE + XOSC_CTRL_OFFSET) = (XOSC_CTRL_ENABLE_VALUE_ENABLE<<XOSC_CTRL_ENABLE_LSB) + XOSC_CTRL_FREQ_RANGE_VALUE_1_15MHZ;
    while(!(REG(XOSC_BASE + XOSC_STATUS_OFFSET) & XOSC_STATUS_STABLE_BITS));

    REG(PLL_SYS_BASE + PLL_FBDIV_INT_OFFSET) = FBDIV;
    REG(PLL_SYS_BASE + PLL_PRIM_OFFSET) = (POSTDIV1<<PLL_PRIM_POSTDIV1_LSB | POSTDIV2<<PLL_PRIM_POSTDIV2_LSB);
    REG(PLL_SYS_BASE + PLL_PWR_OFFSET + REG_ALIAS_CLR_BITS) = PLL_PWR_PD_BITS | PLL_PWR_VCOPD_BITS | PLL_PWR_POSTDIVPD_BITS;
    while(!(REG(PLL_SYS_BASE + PLL_CS_OFFSET) & PLL_CS_LOCK_BITS));

    REG(CLOCKS_BASE + CLOCKS_CLK_SYS_CTRL_OFFSET) = CLOCKS_CLK_SYS_CTRL_SRC_VALUE_CLKSRC_CLK_SYS_AUX; //set sytem clock to pll
    while(REG(CLOCKS_BASE + CLOCKS_CLK_SYS_SELECTED_OFFSET) != 1<<CLOCKS_CLK_SYS_CTRL_SRC_VALUE_CLKSRC_CLK_SYS_AUX);
    REG(CLOCKS_BASE + CLOCKS_CLK_PERI_CTRL_OFFSET) = CLOCKS_CLK_PERI_CTRL_ENABLE_BITS;

    REG(IO_BANK0_BASE + IO_BANK0_GPIO0_CTRL_OFFSET) = GPIO_FUNC_UART; //UART0 TX
    REG(IO_BANK0_BASE + IO_BANK0_GPIO1_CTRL_OFFSET) = GPIO_FUNC_UART; //UART0 RX

    REG(PADS_BANK0_BASE + PADS_BANK0_GPIO0_OFFSET + REG_ALIAS_CLR_BITS) = PADS_BANK0_GPIO0_ISO_BITS;
    REG(PADS_BANK0_BASE + PADS_BANK0_GPIO1_OFFSET + REG_ALIAS_CLR_BITS) = PADS_BANK0_GPIO0_ISO_BITS;
    REG(PADS_BANK0_BASE + PADS_BANK0_GPIO1_OFFSET + REG_ALIAS_SET_BITS) = PADS_BANK0_GPIO0_IE_BITS;

    REG(RESETS_BASE + RESETS_RESET_OFFSET + REG_ALIAS_CLR_BITS) = RESETS_RESET_UART0_BITS;
    while(~(REG(RESETS_BASE + RESETS_RESET_DONE_OFFSET)) & (RESETS_RESET_DONE_UART0_BITS));
    REG(UART0_BASE + UARTIBRD_OFFSET) = IBRD;
    REG(UART0_BASE + UARTFBRD_OFFSET) = FBRD;
    REG(UART0_BASE + UART_UARTLCR_H_OFFSET) = 0b11<<UART_UARTLCR_H_WLEN_LSB; //8bits, no parity, 1 stop bit
    REG(UART0_BASE + UART_UARTCR_OFFSET) = UART_UARTCR_UARTEN_BITS | UART_UARTCR_RXE_BITS | UART_UARTCR_TXE_BITS;
}

int main(){

    double x = 0.0;

    uart_init();

    for(;;){
        getchar();
        printf("%5.1f %19.16f\r\n", x, sin(x));
        x += 0.1;
    }
}
