#define TICKS_BASE 0x40108000
#define   TICKS_TIMER0_CTRL_OFFSET 0x18
#define     TICKS_TIMER0_CTRL_ENABLE_BITS 1<<0
#define   TICKS_TIMER0_CYCLES_OFFSET 0x1c
#define   TICKS_RISCV_CTRL_OFFSET 0x3c
#define     TICKS_RISCV_CTRL_ENABLE_BITS 1<<0
#define   TICKS_RISCV_CYCLES_OFFSET 0x40
