#define TIMER0_BASE 0x400b0000
#define   TIMER_TIMEHW_OFFSET 0x0
#define   TIMER_TIMELW_OFFSET 0x4
#define   TIMER_TIMEHR_OFFSET 0x8
#define   TIMER_TIMELR_OFFSET 0xc
#define   TIMER_ALARM0_OFFSET 0x10
#define   TIMER_INTR_OFFSET 0x3c
#define   TIMER_INTE_OFFSET 0x40
